SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE MEMBER;
TRUNCATE TABLE REFRESH_TOKEN;
TRUNCATE TABLE LINK;
TRUNCATE TABLE LINK_HAS_TAG;
TRUNCATE TABLE TAG;
TRUNCATE TABLE CATEGORY_TAG;

SET REFERENTIAL_INTEGRITY TRUE;